[Review] 01_commonのREADME.mdを更新
Hibikino-Musashi-Home/hma_wrs_sim_ws pull request #4
Opened 2022-03-13 15:08 UTC by TomohiroOno33

更新しました．

2022-03-15 02:17 UTC, TomohiroOno33 commented
@kzht-t 
ご指摘ありがとうございます．
修正完了いたしました．

2022-03-16 01:21 UTC, kzht-t commented on src/01_common/hma_yolact/hma_yolact_pkg/docs/yolact_server.md
> +Publish recognition results with the 3D pose.
@TomohiroOno33 
use_dフラグの追加対応ありがとうございます.
実装上では~get_poseのパラメータとandでパブリッシュするかしないかを切り分けているように見えるので，その確認もお願いしたいです．

2022-03-22 00:45 UTC, TomohiroOno33 commented on src/01_common/hma_yolact/hma_yolact_pkg/docs/yolact_server.md
> +Publish recognition results with the 3D pose.
@kzht-t 
ご確認ありがとうございます．
遅くなりましたが，更新いたしました．

2022-03-24 09:16 UTC, yuka-hashiguchi requested changes
遅くなりすみません．見ました．
こちらも名前に関する指摘は実装に影響するので参考までに・・です．

2022-03-24 09:16 UTC, yuka-hashiguchi commented on src/01_common/hma_yolact/hma_yolact_pkg/docs/yolact_server.md
> +The threshold uses for recognition.
`threshold` でなくて `weight` とか `model` とかかな（コピペミス？）

あとは，デフォルト値を見ると自明ですが，このパラメータが表すものがファイル名なのかパスなのか重みそのものなのか（それはないだろうけど 😅 ）明確なパラメータ名を付けられるとよりよいですね(cfgも)．

2022-03-24 09:16 UTC, yuka-hashiguchi commented on src/01_common/hma_yolact/hma_yolact_pkg/docs/yolact_server.md
> +**~th (float)**
例えば `~score_threshold` にするなど，何の閾値なのか分かるといいですね

2022-03-28 04:30 UTC, TomohiroOno33 commented on src/01_common/hma_common/hma_common_pkg/docs/get_pose_node.md
> +You can see the (x, y, yaw) position on the terminal.
このノードは，座標取りのデバッグ用として使用していたので，ターミナル表示だけになっております．

2022-03-28 04:33 UTC, TomohiroOno33 commented on src/01_common/hma_yolact/hma_yolact_pkg/docs/yolact_server.md
> +**~th (float)**
ドキュメントの修正を行いました．
実装に関わるところは，今後の課題とさせていただきます．
ご指摘ありがとうございます．

2022-03-28 04:40 UTC, yuka-hashiguchi approved these changes
修正確認しました 👍

2022-03-28 04:41 UTC, merged