[Review] 02_sim_robot/tasksのREADME.mdを更新
Hibikino-Musashi-Home/hma_wrs_sim_ws pull request #6
Opened 2022-03-13 15:09 UTC by TomohiroOno33

更新しました．

2022-03-17 09:40 UTC, yuka-hashiguchi requested changes
遅くなってごめんなさい．見ました．
初見の人がノードの挙動と使い方が分かるかなというところに主眼をおいて色々コメントしましたが，実装との兼ね合いもあると思うので「次から気を付けます」でもOKです 😄

2022-03-17 09:40 UTC, yuka-hashiguchi commented on src/02_sim_robot/tasks/hma_hsr_cu_pkg/docs/estimate_orientation_node.md
> +This node provides the function to estimate the cutlery and marker orientation using template match.
template match -> template matchingの方がいいかな？

2022-03-17 09:40 UTC, yuka-hashiguchi commented on src/02_sim_robot/tasks/hma_hsr_cu_pkg/docs/estimate_orientation_node.md
> +If `/sm_cu_node/oreint_item/flag` in rosparam is `True`, it is executed.
フラグの名前は `is_hogehoge` にすると説明を詳しく書かなくても分かりやすいかもしれませんね

2022-03-17 09:40 UTC, yuka-hashiguchi commented on src/02_sim_robot/tasks/hma_hsr_cu_pkg/docs/estimate_orientation_node.md
> +
detect_drivable_area_serverのREADMEみたいに，このノードが持つROSのインタフェースが書かれているとより分かりやすいかもしれません．

2022-03-17 09:40 UTC, yuka-hashiguchi commented on src/02_sim_robot/tasks/hma_hsr_cu_pkg/docs/estimate_orientation_node.md
> +If `/sm_cu_node/target_obj/id` in rosparam (which stores the ID of the grasped object) is cutlery (`30`, `31`, `32`), then matching is performed with the cutlery template image, and orientation estim
パラメータの説明は型（と，あればデフォルト値）も書いておくと親切ですね．

2022-03-17 09:40 UTC, yuka-hashiguchi commented on src/02_sim_robot/tasks/hma_hsr_cu_pkg/docs/estimate_orientation_node.md
> +The estimated result (left or right as seen from the camera) is set to `/sm_cu_node/oreint_item/direction` in rosparam.
resultもパラメータで設定するのはなぜですか（ソース見れば分かるかな・・）？
`orient_item/direction` はsetされた後1回getすればいい情報でしょうか？
そうすると自分ならサービスで実装したくなるなと思いました．

2022-03-17 09:40 UTC, yuka-hashiguchi commented on src/02_sim_robot/tasks/hma_hsr_cu_pkg/docs/sm_cu_node.md
> +- Init: Initialize state.
せっかく各ノードの説明を書いているので，遷移条件の説明も加えてあげるとよりよさそうです．

2022-03-17 09:40 UTC, yuka-hashiguchi commented on src/02_sim_robot/tasks/hma_hsr_gg_pkg/docs/detect_drivable_area_server.md
> +# detect_drivable_area_server
このREADMEすごくいいですね．使うときに知りたい情報（ROS Spec）がきれいに頭に入ってきます 👍

2022-03-17 09:40 UTC, yuka-hashiguchi commented on src/02_sim_robot/tasks/hma_hsr_gg_pkg/docs/detect_drivable_area_server.md
> +**~d (str)**
説明を読まなくても意味の分かる名前を付けた方がいいですね．`depth_image` かな？

2022-03-17 09:40 UTC, yuka-hashiguchi commented on src/02_sim_robot/tasks/hma_hsr_gg_pkg/docs/detect_drivable_area_server.md
> +**~finish ([std_msgs/Empty.msg](http://docs.ros.org/en/melodic/api/std_msgs/html/msg/Empty.html))**
ここは `~` だとどのノードが吐く `finish` なのか分からないのでsubscriberはフルパスで書いた方がいいかなと思いました（L.40とL.44も）．L.50はフルパスになっているので分かります 👍

2022-03-23 05:52 UTC, TomohiroOno33 commented on src/02_sim_robot/tasks/hma_hsr_gg_pkg/docs/detect_drivable_area_server.md
> +**~finish ([std_msgs/Empty.msg](http://docs.ros.org/en/melodic/api/std_msgs/html/msg/Empty.html))**
まとめて返信させていただきます．

ご確認ありがとうございます．
今回は，ドキュメントの変更のみにとどめて，プログラムに修正が必要なものは今後の課題とさせていただきます．

`estimate_orientation_node`に関しては，設計がすごく悪いと思っていて，今後修正していく予定です．

2022-03-23 10:03 UTC, yuka-hashiguchi approved these changes
対応ありがとうございます 👍

2022-03-25 05:25 UTC, alpha-soliton approved these changes
hashiguchiさんにほぼコメントしきっていただいているので他は問題ないと思います．

2022-03-28 04:21 UTC, merged